services:
  flask:
    image: alexsuf/flask
    container_name: flask
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      TZ: Europe/Moscow
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    command: "python3 /app/app.py"

  postgres:
    image: alexsuf/postgres
    container_name: postgres
    restart: always
    ports:
      - 1111:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
      TZ: Europe/Moscow
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
      - ./on_startup.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: alexsuf/pgadmin
    container_name: pgadmin
    ports:
      - 5050:80   # localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: aleksey.zadonsky@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
      TZ: Europe/Moscow
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
      - ./FILES:/mnt/files 